feat/turoials
shuvijs/shuvijs.org pull request #43
Opened 2022-07-28 03:37 UTC by Ives7

2022-07-28 03:56 UTC, Ives7 commented
<img width="1882" alt="image" src="https://user-images.githubusercontent.com/24537993/181417026-e4a594f1-cdf4-44a9-a615-91e14bf35715.png">

2022-07-28 03:57 UTC, Ives7 commented
<img width="1882" alt="image" src="https://user-images.githubusercontent.com/24537993/181417074-ad2847fa-9135-4765-9368-0f774bf45b57.png">

2022-07-28 03:58 UTC, Ives7 commented
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/24537993/181417168-777a41ff-8a95-4298-a855-fd6d8c86e6c5.png">

2022-07-28 03:59 UTC, Ives7 commented
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/24537993/181417226-a2fb91ae-9b4d-4244-a22a-604a13508f63.png">
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/24537993/181417254-93c49116-6891-4dd6-869a-84d022dfec23.png">
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/24537993/181417278-6ca90bd2-3cef-40af-8a37-8b23059ab803.png">
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/24537993/181417301-0cdfd184-0535-4c68-8a19-3253145b81a0.png">
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/24537993/181417320-89d3653e-7137-4e96-bd75-0da1bfc338f5.png">
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/24537993/181417334-aebe0914-c899-4158-83f9-270900e06918.png">

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/24537993/181417357-73438bc3-928b-4263-96cd-2666eebdb7b6.png">
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/24537993/181417380-4e808000-1b3d-4d0a-9db3-5cf62efb4f4b.png">

2022-07-28 04:04 UTC, liximomo requested changes

2022-07-28 04:04 UTC, liximomo commented on docs/tutorials.md
>  - [node ^14.x](https://github.com/nodejs/Release)
16.x

2022-07-28 04:04 UTC, liximomo commented on docs/tutorials.md
>  ## Blog
改成 Create your first app, 直接叫blog我还以为后面的内容是我们的博客呢

2022-07-28 04:39 UTC, Ives7 commented
finnal /posts

<img width="1880" alt="image" src="https://user-images.githubusercontent.com/24537993/181421762-da0764a2-e5d8-4056-a5b8-6c0282db0449.png">

2022-07-28 04:39 UTC, Ives7 commented
finnal /posts/:id
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/24537993/181421845-b836aa78-48cd-4611-81c2-3a16b41aacd6.png">

2022-07-29 01:39 UTC, Ives7 commented
<img width="961" alt="image" src="https://user-images.githubusercontent.com/24537993/181664954-1baa8e2a-c32b-4268-969c-7fd5e81d1dcb.png">

2022-07-29 01:40 UTC, Ives7 commented
<img width="960" alt="image" src="https://user-images.githubusercontent.com/24537993/181665061-801b4270-bcd9-485a-8855-b8110a9ac8a7.png">

2022-07-29 02:48 UTC, merged