docs: update Polyfills
shuvijs/shuvijs.org pull request #57
Opened 2023-04-19 06:27 UTC by wangjinyang

2023-04-19 08:42 UTC, liximomo requested changes

2023-04-19 08:42 UTC, liximomo commented on docs/guides/index.md
> -- [**Promise**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/old-reference/Global_Objects/Promise)
为什么删除了promise

2023-04-20 03:05 UTC, wangjinyang commented on docs/guides/index.md
> -- [**Promise**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/old-reference/Global_Objects/Promise)
https://nextjs.org/docs/basic-features/supported-browsers-features#polyfills

参照next改的，他们也给删除了

2023-04-20 07:55 UTC, liximomo commented on docs/guides/index.md
> -- [**Promise**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/old-reference/Global_Objects/Promise)
他们不只是删文档吧，他们是代码里也删了，我们polyfill代码那边可没删吧

2023-04-20 08:02 UTC, wangjinyang commented on docs/guides/index.md
> -- [**Promise**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/old-reference/Global_Objects/Promise)
https://github.com/vercel/next.js/blob/canary/packages/next-polyfill-nomodule/src/index.js#L53-L55

next Promise 的polyfills代码没删，文档中删除了

shuvi的Promise polyfills代码也在

2023-04-20 14:10 UTC, liximomo commented on docs/guides/index.md
> -- [**Promise**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/old-reference/Global_Objects/Promise)
那他们这个操作有些迷的，我不是很理解，也很难表示赞同

2023-04-21 05:47 UTC, merged