docs: update example
shuvijs/shuvijs.org pull request #62
Opened 2023-05-30 07:58 UTC by wangjinyang

2023-05-30 08:10 UTC, evenchange4 requested changes

2023-05-30 08:10 UTC, evenchange4 commented on docs/guides/data-fetching.md
> +// anyModule.js
```suggestion
// anyModule.js
// ✅ OK - It is safe to define a single loader function in the anyModule.js.
```

2023-05-30 08:10 UTC, evenchange4 commented on docs/guides/data-fetching.md
> +// highlight-next-line
```suggestion
// highlight-next-line
// ❌ Wrong - Don't define and export modules related to views.
```

2023-05-30 08:10 UTC, evenchange4 commented on docs/guides/data-fetching.md
> +// highlight-next-line
```suggestion
// highlight-next-line
// ❌ Wrong - Don't define and export modules that are unrelated to the loader.
```

2023-05-30 08:10 UTC, evenchange4 commented on docs/guides/data-fetching.md
> +export { default, loader } from "./anyModule";
```suggestion
// ❌ Wrong -  Don't re-export default and loader from the same file.
export { default, loader } from "./anyModule";

// ✅ OK - It is safe to export a single loader function.
export { loader } from "./anyModule";
```

2023-05-31 00:48 UTC, liximomo reviewed
/lgtm

2023-05-31 00:48 UTC, merged